services:
  mariadb:
    image: mariadb:10.6
    container_name: wedding_mariadb
    restart: unless-stopped
    environment:
      MARIADB_USER: "${DB_WEDDING_SITE_USERNAME}"
      MARIADB_PASSWORD: "${DB_WEDDING_SITE_PASSWORD}"
      MARIADB_DATABASE: "wedding_site"
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MONITORING_PASSWORD: "${MONITORING_PASSWORD}"
      TZ: "UTC"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "monitoring", "-p${MONITORING_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - wedding_network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=50
      - --innodb-buffer-pool-size=128M
      - --expire-logs-days=0

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/wedding_site
      - SPRING_DATASOURCE_USERNAME=${DB_WEDDING_SITE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_WEDDING_SITE_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET:-default-secret-key}
      - DEFAULT_PASSWORD=mywedding
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - wedding_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
#    depends_on:
#      backend:
#        condition: service_healthy
    networks:
      - wedding_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  mariadb_data:
    name: wedding_mariadb_data

networks:
  wedding_network:
    name: wedding_network
    driver: bridge

