services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: wedding_rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - wedding_network
    depends_on:
      mariadb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M

  mariadb:
    image: mariadb:10.6
    container_name: wedding_mariadb
    restart: unless-stopped
    environment:
      MARIADB_USER: "${DB_WEDDING_SITE_USERNAME}"
      MARIADB_PASSWORD: "${DB_WEDDING_SITE_PASSWORD}"
      MARIADB_DATABASE: "wedding_site"
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MONITORING_PASSWORD: "${MONITORING_PASSWORD}"
      TZ: "UTC"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "monitoring", "-p${MONITORING_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - wedding_network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=50
      - --innodb-buffer-pool-size=128M
      - --expire-logs-days=0

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/wedding_site
      - SPRING_DATASOURCE_USERNAME=${DB_WEDDING_SITE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_WEDDING_SITE_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - wedding_network
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
#    depends_on:
#      backend:
#        condition: service_healthy
    networks:
      - wedding_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  rabbitmq_data:
    name: wedding_rabbitmq_data
  rabbitmq_logs:
    name: wedding_rabbitmq_logs
  mariadb_data:
    name: wedding_mariadb_data

networks:
  wedding_network:
    name: wedding_network
    driver: bridge

