server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot
    static_configs:
      - targets:
          - localhost
        labels:
          app: wedding-backend
          component: api
          __path__: /var/log/wedding/wedding-app*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            traceId: traceId
            requestId: requestId
            userId: userId
      - labels:
          traceId:
          requestId:
          userId:
          level:

  - job_name: auth-logs
    static_configs:
      - targets:
          - localhost
        labels:
          app: wedding-backend
          component: auth
          __path__: /var/log/wedding/auth*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            traceId: traceId
            requestId: requestId
            userId: userId
            authResult: authResult
      - labels:
          traceId:
          requestId:
          userId:
          authResult:

  - job_name: frontend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          app: wedding-frontend
          component: angular
          __path__: /var/log/wedding/frontend*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            traceId: traceId
            requestId: requestId
            clientUrl: clientUrl
            source: source
      - labels:
          traceId:
          requestId:
          source:
          level:

  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          app: wedding-frontend
          component: nginx
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            status: status
            request_id: request_id
            trace_id: trace_id
            client_ip: client_ip
            forwarded_for: forwarded_for
      - labels:
          trace_id:
          request_id:
          status: