global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'wedding-backend'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          application: 'wedding-frontend'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          application: 'loki'

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld-exporter:9104']
        labels:
          application: 'mariadb'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'prometheus'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          application: 'node'