spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/wedding_site
    username: ${DB_WEDDING_SITE_USERNAME}
    password: ${DB_WEDDING_SITE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: wedding-backend
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
