spring:
  profiles:
    active: dev
#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    fail-on-missing-locations: false
  datasource:
    url: jdbc:mariadb://localhost:3306/wedding_site
    username: ${DB_WEDDING_SITE_USERNAME}
    password: ${DB_WEDDING_SITE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: wedding-backend
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  security:
    jwt:
#      should be properly secured in production environments
      secret: ${JWT_SECRET:KkYzn0UFeYNKEgtnslOVCmR96iUfAMDM07EUzk5MSZkfXl49aCu4rdmsqbbgD5MlZiIH40sScWKwCFbZlqi9PA==}
      expiration: 7200000
management:
  endpoints:
    web:
      base-path: /adminInfo
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-components: when_authorized
      show-details: when_authorized
      roles: "ADMIN"
      probes:
        enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    mail:
      enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    enable:
      jvm: true
      process: true
      system: true
      jdbc: true
      http: true
    tags:
      application: ${spring.application.name}
      service: wedding-backend

# Common logging config
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    com.zlatenov.wedding_backend: INFO

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 500

logging:
  level:
    com.zlatenov.wedding_backend: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.zlatenov.wedding_backend: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN