spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    fail-on-missing-locations: false
  datasource:
    url: jdbc:mariadb://mariadb:3306/wedding_site
    username: ${DB_WEDDING_SITE_USERNAME}
    password: ${DB_WEDDING_SITE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: wedding-backend
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
    db:
      enabled: true