name: Docker Compose Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-validation:
    runs-on: ubuntu-latest

    env:
      DB_WEDDING_SITE_USERNAME: ${{ secrets.DB_WEDDING_SITE_USERNAME }}
      DB_WEDDING_SITE_PASSWORD: ${{ secrets.DB_WEDDING_SITE_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      MONITORING_PASSWORD: ${{ secrets.MONITORING_PASSWORD }}
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pika

      - name: Install Docker Compose V2
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.31.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Validate Docker Compose configuration
        run: docker compose config

      - name: Build Docker images
        run: docker compose build

      - name: Start containers
        run: |
          docker compose up -d
          echo "Waiting for containers to initialize..."
          sleep 30

      - name: Check container health
        run: |
          docker compose ps
          docker compose logs
          if [ "$(docker compose ps --format json | jq -r '.[].Health' | grep -v healthy)" ]; then
            echo "Some containers are not healthy"
            exit 1
          fi

      - name: Test MariaDB
        run: |
          docker exec wedding_mariadb mysql -u${DB_WEDDING_SITE_USERNAME} -p${DB_WEDDING_SITE_PASSWORD} -e "SHOW DATABASES;"

      - name: Wait for RabbitMQ to be ready
        run: |
          echo "Waiting for RabbitMQ..."
          timeout=30
          while [ $timeout -gt 0 ]; do
            if curl -sf http://localhost:15672/api/healthchecks/node; then
              echo "RabbitMQ is ready"
              break
            fi
            sleep 1
            ((timeout--))
          done
          if [ $timeout -eq 0 ]; then
            echo "RabbitMQ failed to start"
            docker compose logs rabbitmq
            exit 1
          fi

      - name: Run Python Test
        run: python test_rabbitmq.py
        env:
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}

      - name: Stop containers
        if: always()
        run: docker compose down -v